language: python

python:
    - 2.7

env:
  - TWISTED=svn+svn://svn.twistedmatrix.com/svn/Twisted/trunk
  - TWISTED=Twisted==13.0.0
  - TWISTED=Twisted==12.3.0
  - TWISTED=Twisted==12.2.0
  - TWISTED=Twisted==12.1.0

install:
  - pip install $TWISTED --use-mirrors
  - pip install simplejson --use-mirrors
  - pip install txAMQP --use-mirrors
  - pip install scribe --use-mirrors
  - pip install thrift --use-mirrors

script:
  - trial udplog